{{- if .Values.roleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.serviceAccount.namespace | default .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (include "ocp-security.name" .) }}
    namespace: {{ .Values.serviceAccount.namespace | default .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.roleBinding.roleName }}
  apiGroup: {{ .Values.roleBinding.apiGroup | default "rbac.authorization.k8s.io" }}
{{- end }}
