{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "ocp-security.name" .) }}
  namespace: {{ .Values.serviceAccount.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ocp-security.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
